name: Build and Publish Backstage Docker Image

on:
  push:
    branches:
      - main  # or your default branch
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: development  # Specifies the environment to use

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.11.1'  # specify your Node.js version

    - name: Install dependencies with Yarn
      run: yarn install

    - name: Build Backstage app
      run: yarn run build:all

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        push: false
        tags: gonzalovazquez/fragment7:latest  # Change to your Docker Hub username/repository
  
  publish:
k
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:oidc-provider/token.actions.githubusercontent.com
        aws-region: ${{ vars.AWS_REGION}}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build Docker image
      run: |
        docker build -t gonzalovazquez/fragmen7:latest .

    - name: Tag Docker image
      run: |
        docker tag gonzalovazquez/fragmen7:latest ${{ vars.REGISTRY }}:latest

    - name: Publish Docker image to AWS ECR
      run: |
        docker push ${{ vars.REGISTRY }}:latest

